$('.owl-carousel').owlCarousel({
    loop:true,
    margin:80,
    responsiveClass:true,
    responsive:{
        0:{
            items:1,
        },
        768:{
            items:2,
        },
        1100:{
            items:4,
        },
        1400:{
            items:5,
            loop:false,
        }
    }
})

